# This is a basic workflow to help you get started with Actions

name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
  # Triggers the workflow on push or pull request events but only for the "main" branch
jobs:
  # This workflow contains a single job called "build"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variables
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Sept up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python main.py

